name: Publish Smithy Client to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/
          scope: "@mshanah98"

      - name: Build Smithy client
        run: ./gradlew smithyBuild

      - name: Install dependencies for SDK
        working-directory: build/smithyprojections/SmithyDemo/typescript/typescript-codegen
        run: yarn install --frozen-lockfile

      - name: Publish to GitHub Packages
        working-directory: build/smithyprojections/SmithyDemo/typescript/typescript-codegen
        run: npm publish --access=restricted --registry=https://npm.pkg.github.com --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Publish OpenAPI Spec to GitHub Packages
      - name: Publish OpenAPI Spec to GitHub Packages
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -X POST \
            -F "file=@build/smithyprojections/SmithyDemo/openapi/openapi.yaml" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/assets?name=openapi.yaml"